version: 2

sources:
  - name: home_assistant
    meta:
      external_location: "delta_scan('s3://{{ env_var('ENVIRONMENT') }}/base/home_assistant/{name}')"
    tables:
      - name: states
        meta:
          dagster:
            asset_key: "dlt_home_assistant_source_states"
      - name: states__value
        meta:
          dagster:
            asset_key: "dlt_home_assistant_source_states"
  - name: grist
    meta:
      external_location: "delta_scan('s3://{{ env_var('ENVIRONMENT') }}/base/grist/{name}')"
    tables:
      - name: orgs
        columns:
          - name: id
            tests:
              - unique
      - name: all
      - name: sets
  - name: spiir
    meta:
      external_location: "delta_scan('s3://{{ env_var('ENVIRONMENT') }}/base/spiir/{name}')"
    tables:
      - name: transactions
        columns:
          - name: id
            tests:
              - unique
        meta:
          dagster:
            asset_key: "dlt_spiir_source_transactions"
  - name: calendar
    meta:
      external_location: "delta_scan('s3://{{ env_var('ENVIRONMENT') }}/base/calendar/{name}')"
    tables:
      - name: calendar
        columns:
          - name: date_actual
            tests:
              - unique
  - name: rebrickable
    meta:
      external_location: "delta_scan('s3://{{ env_var('ENVIRONMENT') }}/base/rebrickable/{name}')"
    tables:
      - name: lego_sets
        columns:
          - name: set_num
            tests:
              - unique
      - name: lego_minifigs
        columns:
          - name: set_num
            #tests:
              #- unique
      - name: lego_parts
        columns:
          - name: inv_part_id
            tests:
              - unique
      - name: lego_alternates
        columns:
          - name: set_num
            tests:
              - unique
  - name: todoist
    meta:
      external_location: "delta_scan('s3://{{ env_var('ENVIRONMENT') }}/base/todoist/{name}')"
    tables:
      - name: filters
        meta:
          dagster:
            asset_key: "dlt_todoist_source_filters"
      - name: items
        meta:
          dagster:
            asset_key: "dlt_todoist_source_items"
      - name: labels
        meta:
          dagster:
            asset_key: "dlt_todoist_source_labels"
      - name: live_notifications
        meta:
          dagster:
            asset_key: "dlt_todoist_source_live_notifications"
      - name: projects
        meta:
          dagster:
            asset_key: "dlt_todoist_source_projects"
      - name: reminders
        meta:
          dagster:
            asset_key: "dlt_todoist_source_reminders"
  - name: dawa
    meta:
      external_location: "delta_scan('s3://{{ env_var('ENVIRONMENT') }}/base/dawa/{name}')"
    tables:
      - name: dawa_locations
        meta:
          dagster:
            asset_key: "dlt_dawa_source_dawa_locations"