name: Daily Data Core
'on':
  schedule:
  - cron: '*/30 * * * *'
  workflow_dispatch: null
env:
  DESTINATION__BUCKET_URL: ${{ secrets.DESTINATION__BUCKET_URL }}
  DESTINATION__ENDPOINT_URL: ${{ secrets.DESTINATION__ENDPOINT_URL }}
  DESTINATION__AWS_ACCESS_KEY_ID: ${{ secrets.DESTINATION__AWS_ACCESS_KEY_ID }}
  DESTINATION__AWS_SECRET_ACCESS_KEY: ${{ secrets.DESTINATION__AWS_SECRET_ACCESS_KEY }}
  DESTINATION__USE_SSL: false

  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  HOME_ASSISTANT_HOST: ${{ secrets.HOME_ASSISTANT_HOST }}
  HOME_ASSISTANT_PORT: ${{ secrets.HOME_ASSISTANT_PORT }}
  HOME_ASSISTANT_TOKEN: ${{ secrets.HOME_ASSISTANT_TOKEN }}

jobs:
  maybe_skip:
    runs-on: [self-hosted, linux, docker]
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
    - id: skip_check
      uses: fkirc/skip-duplicate-actions@v5
      with:
        concurrent_skipping: always
        skip_after_successful_duplicate: 'false'
        do_not_skip: '[]'
  run_github_api_pipeline:
    needs: maybe_skip
    if: needs.maybe_skip.outputs.should_skip != 'true'
    runs-on: [self-hosted, linux, docker]
    steps:
    - name: Check out
      uses: actions/checkout@v3
    - name: Setup uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        cache-dependency-glob: "dlt_project/uv.lock"
    - name: Setup Python with uv
      run: |
        cd dlt_project
        uv python install 3.12
    - name: Install dependencies
      run: |
        cd dlt_project
        uv sync --frozen
    - name: Run pipeline script
      run: |
        cd dlt_project
        uv run sources/github_api_pipeline.py
  run_home_assistant_pipeline:
    needs: maybe_skip
    if: needs.maybe_skip.outputs.should_skip != 'true'
    runs-on: [self-hosted, linux, docker]
    steps:
    - name: Check out
      uses: actions/checkout@v3
    - name: Setup uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        cache-dependency-glob: "dlt_project/uv.lock"
    - name: Setup Python with uv
      run: |
        cd dlt_project
        uv python install 3.12
    - name: Install dependencies
      run: |
        cd dlt_project
        uv sync --frozen
    - name: Run pipeline script
      run: |
        cd dlt_project
        uv run sources/home_assistant.py