name: Daily Data Core
'on':
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

env:
  DESTINATION__FILESYSTEM__BUCKET_URL: s3://prod/base/
  DESTINATION__FILESYSTEM__CREDENTIALS__ENDPOINT_URL: ${{secrets.FILESYSTEM_ENDPOINT_URL }}
  DESTINATION__FILESYSTEM__CREDENTIALS__AWS_ACCESS_KEY_ID: ${{secrets.FILESYSTEM_AWS_ACCESS_KEY_ID }}
  DESTINATION__FILESYSTEM__CREDENTIALS__AWS_SECRET_ACCESS_KEY: ${{secrets.FILESYSTEM_AWS_SECRET_ACCESS_KEY }}
  DESTINATION__FILESYSTEM__CREDENTIALS__REGION_NAME: eu-west-1
  DESTINATION__FILESYSTEM__KWARGS__USE_SSL: false

  # Home Assistant source configuration - using simpler env var names that dlt looks for
  SOURCES__HOME_ASSISTANT_HOST: ${{ secrets.HOME_ASSISTANT_HOST }}
  SOURCES__HOME_ASSISTANT_PORT: ${{ secrets.HOME_ASSISTANT_PORT }}
  SOURCES__HOME_ASSISTANT_TOKEN: ${{ secrets.HOME_ASSISTANT_TOKEN }}

  # SPIIR source configuration
  SOURCES__SPIIR_BASE_URL: ${{ secrets.SPIIR_BASE_URL }}
  SOURCES__SPIIR_EMAIL: ${{ secrets.SPIIR_EMAIL }}
  SOURCES__SPIIR_PASSWORD: ${{ secrets.SPIIR_PASSWORD }}

  # Todoist source configuration
  SOURCES__TODOIST_URL: ${{ secrets.TODOIST_URL }}
  SOURCES__TODOIST_TOKEN: ${{ secrets.TODOIST_TOKEN }}

  # Dawa source configuration
  SOURCES__DAWA_DAWA_BASE_URL: https://api.dataforsyningen.dk
  SOURCES__DAWA_DUCKDB_ENDPOINT: ${{ secrets.DUCKDB_ENDPOINT }}
  SOURCES__DAWA_DUCKDB_KEY_ID: ${{ secrets.DUCKDB_KEY_ID }}
  SOURCES__DAWA_DUCKDB_SECRET: ${{ secrets.DUCKDB_SECRET }}
  SOURCES__DAWA_DUCKDB_REGION: eu-west-1
  SOURCES__DAWA_DUCKDB_USE_SSL: false
  SOURCES__DAWA_DUCKDB_URL_STYLE: path


jobs:

  maybe_skip_home_assistant_pipeline:
    runs-on: [self-hosted, linux, docker]
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
    - id: skip_check
      uses: fkirc/skip-duplicate-actions@v5
      with:
        concurrent_skipping: always
        skip_after_successful_duplicate: 'false'
        do_not_skip: '[]'

  run_home_assistant_pipeline:
    needs: maybe_skip_home_assistant_pipeline
    if: needs.maybe_skip_home_assistant_pipeline.outputs.should_skip != 'true'
    runs-on: [self-hosted, linux, docker]
    steps:
    - name: Check out
      uses: actions/checkout@v3
    - name: Setup DLT Project
      uses: ./.github/actions/setup-dlt-project
    - name: Run pipeline script
      run: |
        cd dlt_project
        uv run sources/home_assistant.py

  maybe_skip_spiir_pipeline:
    runs-on: [self-hosted, linux, docker]
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
    - id: skip_check
      uses: fkirc/skip-duplicate-actions@v5
      with:
        concurrent_skipping: always
        skip_after_successful_duplicate: 'false'
        do_not_skip: '[]'

  run_spiir_pipeline:
    needs: maybe_skip_spiir_pipeline
    if: needs.maybe_skip_spiir_pipeline.outputs.should_skip != 'true'
    runs-on: [self-hosted, linux, docker]
    steps:
    - name: Check out
      uses: actions/checkout@v3
    - name: Setup DLT Project
      uses: ./.github/actions/setup-dlt-project
    - name: Run pipeline script
      run: |
        cd dlt_project
        uv run sources/spiir.py
  
  maybe_skip_todoist_pipeline:
    runs-on: [self-hosted, linux, docker]
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
    - id: skip_check
      uses: fkirc/skip-duplicate-actions@v5
      with:
        concurrent_skipping: always
        skip_after_successful_duplicate: 'false'
        do_not_skip: '[]'

  run_todoist_pipeline:
    needs: maybe_skip_todoist_pipeline
    if: needs.maybe_skip_todoist_pipeline.outputs.should_skip != 'true'
    runs-on: [self-hosted, linux, docker]
    steps:
    - name: Check out
      uses: actions/checkout@v3
    - name: Setup DLT Project
      uses: ./.github/actions/setup-dlt-project
    - name: Run pipeline script
      run: |
        cd dlt_project
        uv run sources/todoist.py

  maybe_skip_dawa_pipeline:
    runs-on: [self-hosted, linux, docker]
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
    - id: skip_check
      uses: fkirc/skip-duplicate-actions@v5
      with:
        concurrent_skipping: always
        skip_after_successful_duplicate: 'false'
        do_not_skip: '[]'

  run_dawa_pipeline:
    needs: maybe_skip_dawa_pipeline
    if: needs.maybe_skip_dawa_pipeline.outputs.should_skip != 'true'
    runs-on: [self-hosted, linux, docker]
    steps:
    - name: Check out
      uses: actions/checkout@v3
    - name: Setup DLT Project
      uses: ./.github/actions/setup-dlt-project